// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsoc_top.h for the primary calling header

#ifndef VERILATED_VSOC_TOP___024ROOT_H_
#define VERILATED_VSOC_TOP___024ROOT_H_  // guard

#include "verilated_heavy.h"

//==========

class Vsoc_top__Syms;
class Vsoc_top_VerilatedVcd;
class Vsoc_top_cv32e40x_if_xif;
class Vsoc_top_cv32e40x_if_c_obi;


//----------

VL_MODULE(Vsoc_top___024root) {
  public:
    // CELLS
    Vsoc_top_cv32e40x_if_xif* __PVT__soc_top__DOT__xif;
    Vsoc_top_cv32e40x_if_c_obi* __PVT__soc_top__DOT__cpu_inst__DOT__m_c_obi_instr_if;

    // PORTS
    VL_IN8(clk_i,0,0);
    VL_IN8(rst_ni,0,0);

    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__clk;
        CData/*0:0*/ soc_top__DOT__instr_gnt;
        CData/*0:0*/ soc_top__DOT__instr_rvalid;
        CData/*0:0*/ soc_top__DOT__data_gnt;
        CData/*0:0*/ soc_top__DOT__data_rvalid;
        CData/*0:0*/ soc_top__DOT__vpu_mem_valid;
        CData/*0:0*/ soc_top__DOT__vpu_mem_result_valid;
        CData/*0:0*/ soc_top__DOT__cpu_data_access_q;
        CData/*0:0*/ soc_top__DOT__cpu_instr_access_q;
        CData/*0:0*/ soc_top__DOT__vpu_mem_access_q;
        CData/*0:0*/ soc_top__DOT__vpu_mem_we_q;
        CData/*3:0*/ soc_top__DOT__vpu_mem_id_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__lsu_busy;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__lsu_interruptible;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__last_op_if;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__last_op_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__last_op_ex;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__abort_op_if;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__abort_op_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__abort_op_wb;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__rf_re_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__csr_counter_read;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__lsu_split_ex;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__lsu_err_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__lsu_valid_1;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__csr_mtvec_init_if;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__csr_illegal;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__xif_csr_error_ex;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__irq_req_ctrl;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__sleep_unit_i__DOT__fetch_enable_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__sleep_unit_i__DOT__core_busy_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__sleep_unit_i__DOT__core_clock_gate_i__DOT__clk_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__if_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__illegal_c_insn;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instr_compressed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_resp_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_trans_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instr_valid;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__xif_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__seq_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__seq_last;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__seq_tbljmp;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__seq_pushpop;
        CData/*4:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instr_meta_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ptr_access;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_ptr_resp;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__fetch_priv_lvl_resp;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__state_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__next_state;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_ptr_access_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_priv_lvl_q;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_cnt_n;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_cnt_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__outstanding_cnt_n;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__outstanding_cnt_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_incoming_ins;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__pop_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__complete_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__complete_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_flush_n;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_flush_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__n_flush_branch;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__bus_err_unaligned;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__mpu_status_unaligned;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_valid_gated;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr_priv_lvl_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_clic_ptr_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_mret_ptr_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__is_tbljmp_ptr_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__ptr_fetch_accepted_q;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_n;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_int;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr_n;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__rptr2;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__wptr;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__wptr_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__aligned_is_compressed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__unaligned_is_compressed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__pma_err;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_block_core;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_block_bus;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_err_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_err_trans_ready;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_status;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__state_q;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__state_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instruction_obi_i__DOT__state_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instruction_obi_i__DOT__next_state;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__instr_cnt_q;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_instr;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_load;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_store;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_move_a2s;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_move_s2a;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_state_n;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_state_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_first_fsm;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__seq_last_fsm;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__instr_is_pointer;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__ready_fsm;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__dmove_legal_dest_a2s;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__rf_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__alu_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__mul_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__div_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__lsu_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__csr_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__sys_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__illegal_insn;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__instr_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__xif_waiting;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__xif_insn_accept;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__xif_insn_reject;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__x_ext__DOT__xif_accepted_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__x_ext__DOT__xif_rejected_q;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__instr_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_cmp_result;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__lsu_en_gated;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div_en;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div_clz_result;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__csr_is_illegal;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__shifter_shamt;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__is_equal;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__is_greater;
        VlWide<5>/*159:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__index_nodes;
        VlWide<6>/*191:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__alu_b_cpop_i__DOT__sum;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem_d;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_inv_d;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_inv_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_inv_d;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_inv_q;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__cnt_q;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__cnt_d;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__init_dummy_cnt;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__remainder_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__quotient_en;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__comp_out;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__init_en;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__next_state;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__state;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_signed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__div_rem;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__op_b_is_neg;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_shift;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_state;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_state_next;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_trans_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__alcheck_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_resp_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__buffer_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__buffer_trans_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__filter_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__filter_trans_ready;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__filter_resp_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__bus_trans_valid;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__cnt_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__next_cnt;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__ctrl_update;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__lsu_size_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__lsu_sext_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__lsu_we_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__rdata_offset_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__last_q;
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__be;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__split_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__nonsplit_misaligned_halfword;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__misaligned_access;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__done_0;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__trans_valid_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__xif_res_q;
    };
    struct {
        CData/*3:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__xif_id_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_err;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_block_core;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_block_bus;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_err_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_err_trans_ready;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__mpu_status;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__state_q;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__state_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_block_core;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_block_bus;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_trans_ready;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__align_status;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__state_q;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__align_check_i__DOT__state_n;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__bus_cnt_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__bus_next_cnt;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__core_cnt_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__core_next_cnt;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__bus_trans_accepted;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__outstanding_q;
        CData/*5:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__response_filter_i__DOT__outstanding_next;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__state;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__next_state;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__push;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_block_core;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_block_bus;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_trans_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_trans_ready;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__state_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__state_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__instr_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__wb_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_exception;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__xif_waiting;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_mpu_status_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_align_status_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_valid_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_mpu_status;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_align_status;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_valid;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__csr_we_int;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__csr_en_gated;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__illegal_csr_read;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mepc_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tselect_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tdata1_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tdata2_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tinfo_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dcsr_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dpc_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dscratch0_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dscratch1_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mscratch_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__jvt_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mstatus_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mstatush_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__misa_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mcause_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mtvec_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mip_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mie_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mtval_we;
    };
    struct {
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__priv_lvl_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__priv_lvl_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__jvt_wr_in_wb;
        QData/*63:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_stopcount;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmevent_we;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata1_we_r;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata1_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_we_int;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_we_hit;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata2_we_int;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__trigger_match_if;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__trigger_match_ex;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_addr_low_lsb;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_addr_high_lsb;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__ctrl_fsm_cs;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__ctrl_fsm_ns;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_fsm_cs;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_fsm_ns;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__nmi_pending_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__nmi_is_store_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_mode_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_mode_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__single_step_halt_if_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__single_step_halt_if_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__sys_mret_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__jmp_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__jump_taken_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__mret_ptr_in_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_ex;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_n;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__branch_taken_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__wfi_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__wfe_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fencei_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__dret_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__ebreak_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__trigger_match_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__etrigger_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__xif_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_async_debug;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_sync_debug;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__pending_single_step;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__interrupt_allowed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__nmi_allowed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__async_debug_allowed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__sync_debug_allowed;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_interruptible;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_cause_n;
        CData/*2:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__debug_cause_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__woke_to_debug_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__woke_to_interrupt_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_set;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_clr;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fence_req_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fencei_req_and_ack_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__fencei_ongoing;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__pipe_pc_mux_ctrl;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__wb_counter_event;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__wb_counter_event_gated;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__csr_flush_ack_n;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__csr_flush_ack_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__sequence_in_progress_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__sequence_in_progress_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__id_stage_haltable;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__interrupt_blanking_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_progress_id;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__clic_ptr_in_progress_id_clear;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__x_ext__DOT__commit_valid_q;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__x_ext__DOT__commit_kill_q;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_match;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_match;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_jalr_match;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_ex_hz;
        CData/*1:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_rd_wb_hz;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__csr_write_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__csr_impl_write_in_wb;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_we_ex;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__bypass_i__DOT__rf_we_wb;
        CData/*2:0*/ soc_top__DOT__vpu_inst__DOT__state;
        CData/*2:0*/ soc_top__DOT__vpu_inst__DOT__next_state;
        CData/*6:0*/ soc_top__DOT__vpu_inst__DOT__funct7_q;
        CData/*4:0*/ soc_top__DOT__vpu_inst__DOT__rd_q;
        CData/*4:0*/ soc_top__DOT__vpu_inst__DOT__rs1_q;
        CData/*4:0*/ soc_top__DOT__vpu_inst__DOT__rs2_q;
        CData/*3:0*/ soc_top__DOT__vpu_inst__DOT__id_q;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT__vrf_we;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_start;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_done;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT__vmac_start;
        CData/*2:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__state;
        CData/*2:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__next_state;
        CData/*4:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__word_counter;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__is_load;
        SData/*9:0*/ soc_top__DOT__cpu_inst__DOT__irq_id_ctrl;
        SData/*11:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__csr_raddr;
        SData/*15:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__hpm_events;
        SData/*15:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__hpm_events_raw;
        SData/*10:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__exception_cause_wb;
        SData/*10:0*/ soc_top__DOT__cpu_inst__DOT__controller_i__DOT__controller_fsm_i__DOT__exc_cause;
        IData/*31:0*/ soc_top__DOT__instr_rdata;
        IData/*31:0*/ soc_top__DOT__data_rdata;
        IData/*31:0*/ soc_top__DOT__vpu_mem_addr_q;
        IData/*31:0*/ soc_top__DOT__cycle_count;
        IData/*31:0*/ soc_top__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ soc_top__DOT__unnamedblk2__DOT__i;
        IData/*17:0*/ soc_top__DOT__cpu_inst__DOT__ctrl_byp;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__rf_wdata_wb;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__rf_wdata_ex;
        IData/*27:0*/ soc_top__DOT__cpu_inst__DOT__csr_hz;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__branch_addr_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_trans_addr;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__prefetcher_i__DOT__trans_addr_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__addr_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__addr_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__instr;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__operand_a_fw;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__operand_b_fw;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__imm_i_type;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__cv32e40x_pc_target_i__DOT__pc_target;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_result;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div_clz_data_rev;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__shifter_bb;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__result_shnadd;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__min_minu_result;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__max_maxu_result;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__clz_data_in;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__sel_nodes;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__alu_clz_data;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__quotient_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__quotient_d;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__remainder_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__remainder_d;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__divisor_d;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__add_a_mux;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__add_b_mux;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__div__DOT__div_i__DOT__res_mux;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_al;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_bl;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_ah;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_bh;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_a;
        IData/*16:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_b;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__rdata_ext;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_match;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_match_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__gen_wpt__DOT__wpt_i__DOT__wpt_match_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_wpt_match_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__wb_stage_i__DOT__lsu_wpt_match;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__csr_wdata_int;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__csr_rdata_int;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mepc_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tdata1_rdata;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__tdata2_rdata;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dcsr_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dcsr_rdata;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dpc_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dscratch0_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__dscratch1_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mscratch_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__jvt_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mstatus_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mcause_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mtvec_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mie_n;
        VlWide<32>/*1023:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmevent_q;
        VlWide<32>/*1023:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmevent_n;
        VlWide<32>/*1023:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmevent_rdata;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mcountinhibit_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mcountinhibit_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_write_lower;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_write_upper;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_write_increment;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__jvt_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mepc_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mscratch_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mstatus_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tselect_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata2_n;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata1_n_r;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__tdata2_n_r;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__unnamedblk1__DOT__b;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__unnamedblk2__DOT__b;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tmatch_csr__BRA__0__KET____DOT__tdata1_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tmatch_csr__BRA__0__KET____DOT__tdata2_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tselect_csr_i__DOT__rdata_q;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dscratch0_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dscratch1_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dcsr_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__gen_debug_csr__DOT__dpc_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mcause_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mtvec_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__basic_mode_csrs__DOT__mie_csr_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__1__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__2__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__3__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__4__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__5__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__6__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__7__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__8__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__9__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__10__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__11__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__12__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__13__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__14__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__15__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__16__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__17__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__18__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__19__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__20__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__21__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__22__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__23__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__24__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__25__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__26__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__27__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__28__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__29__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__30__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__gen_rf__BRA__31__KET____DOT__register_write_behavioral__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__gen_basic_interrupt__DOT__int_controller_i__DOT__irq_local_qual;
        IData/*31:0*/ soc_top__DOT__cpu_inst__DOT__gen_basic_interrupt__DOT__int_controller_i__DOT__irq_q;
        IData/*31:0*/ soc_top__DOT__vpu_inst__DOT__scalar_rs1_q;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__vrf_rdata1;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__vrf_rdata2;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__vrf_rdata3;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__vrf_wdata;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_load_data;
        VlWide<8>/*255:0*/ soc_top__DOT__vpu_inst__DOT__mac_result_q;
        IData/*31:0*/ soc_top__DOT__vpu_inst__DOT__vrf_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ soc_top__DOT__vpu_inst__DOT__vrf_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__addr_counter;
        IData/*31:0*/ soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__cycle_count;
        VlWide<3>/*81:0*/ soc_top__DOT__vpu_mem_req;
        QData/*37:0*/ soc_top__DOT__vpu_mem_result;
        VlWide<12>/*352:0*/ soc_top__DOT__cpu_inst__DOT__id_ex_pipe;
        VlWide<8>/*247:0*/ soc_top__DOT__cpu_inst__DOT__ex_wb_pipe;
        VlWide<6>/*190:0*/ soc_top__DOT__cpu_inst__DOT__if_id_pipe;
        VlWide<7>/*200:0*/ soc_top__DOT__cpu_inst__DOT__ctrl_fsm;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_instr;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instr_decompressed;
        QData/*37:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__core_trans;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__seq_instr;
        VlWide<4>/*104:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_q;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT__resp_n;
        VlWide<3>/*67:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__pma_i__DOT__pma_cfg;
    };
    struct {
        QData/*37:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__instruction_obi_i__DOT__obi_a_req_q;
        QData/*44:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_i_ctrl;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_i_ctrl_int;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_m_ctrl;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_m_ctrl_int;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_a_ctrl_int;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_b_ctrl_int;
        QData/*54:0*/ soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT__decoder_i__DOT__decoder_ctrl_mux;
        QData/*63:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__shifter_tmp;
        QData/*32:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_acc;
        QData/*32:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_acc_next;
        QData/*32:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__mulh_acc_res;
        QData/*33:0*/ soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__mul__DOT__mult_i__DOT__result;
        VlWide<3>/*76:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__trans;
        VlWide<3>/*80:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_trans;
        VlWide<3>/*70:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_resp;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__filter_resp;
        VlWide<3>/*80:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__bus_trans;
        QData/*63:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__rdata_aligned;
        VlWide<3>/*67:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_i__DOT__pma_cfg;
        VlWide<3>/*80:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__trans_q;
        VlWide<64>/*2047:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_q;
        VlWide<64>/*2047:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_n;
        VlWide<64>/*2047:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_rdata;
        VlWide<64>/*2047:0*/ soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__mhpmcounter_increment;
        VlUnpacked<IData/*31:0*/, 8192> soc_top__DOT__memory;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT__rf_raddr_id;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__cpu_inst__DOT__rf_rdata_id;
        VlUnpacked<CData/*4:0*/, 1> soc_top__DOT__cpu_inst__DOT__rf_waddr;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__rf_wdata;
        VlUnpacked<CData/*0:0*/, 1> soc_top__DOT__cpu_inst__DOT__rf_we;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_n;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_q;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata2_q;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata1_rdata;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__tdata2_rdata;
        VlUnpacked<CData/*3:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__lsu_byte_addr_match;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__exception_match;
        VlUnpacked<CData/*1:0*/, 1> soc_top__DOT__cpu_inst__DOT__cs_registers_i__DOT__debug_triggers_i__DOT__gen_triggers__DOT__mcontrol6_hit_resolved;
        VlUnpacked<IData/*31:0*/, 32> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__we_dec;
        VlUnpacked<VlWide<8>/*255:0*/, 32> soc_top__DOT__vpu_inst__DOT__vrf_inst__DOT__vrf;
    };

    // LOCAL VARIABLES
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*4:0*/ soc_top__DOT__cpu_inst__DOT____Vcellout__gen_basic_interrupt__DOT__int_controller_i__irq_id_ctrl_o;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound1;
        CData/*0:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound2;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT____Vcellinp__vlsu_inst__start_store_i;
        CData/*0:0*/ soc_top__DOT__vpu_inst__DOT____Vcellinp__vlsu_inst__start_load_i;
        CData/*4:0*/ __Vfunc_sn_to_regnum__2__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__2__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__3__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__3__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__4__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__4__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__5__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__5__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__6__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__6__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__7__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__7__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__8__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__8__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__9__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__9__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__10__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__10__snum;
        CData/*4:0*/ __Vfunc_sn_to_regnum__11__Vfuncout;
        CData/*4:0*/ __Vfunc_sn_to_regnum__11__snum;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__29__Vfuncout;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__29__next_value;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__32__Vfuncout;
        CData/*3:0*/ __Vfunc_mcontrol2_6_match_resolve__32__next_value;
        CData/*0:0*/ __Vdly__soc_top__DOT__vpu_mem_access_q;
        CData/*0:0*/ __Vdly__soc_top__DOT__vpu_mem_we_q;
        CData/*3:0*/ __Vdly__soc_top__DOT__vpu_mem_id_q;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v0;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v1;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v2;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v3;
        CData/*0:0*/ __Vdly__soc_top__DOT__cpu_data_access_q;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v4;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v5;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v6;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__memory__v7;
        CData/*0:0*/ __Vdly__soc_top__DOT__cpu_instr_access_q;
        CData/*4:0*/ __Vdly__soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__word_counter;
        CData/*2:0*/ __Vdly__soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__state;
        CData/*3:0*/ __Vdly__soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__instr_cnt_q;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v1;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v2;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v3;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v4;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v5;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v6;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v7;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v8;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v9;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v10;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v11;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v12;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v13;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v14;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v15;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v16;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v17;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v18;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v19;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v20;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v21;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v22;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v23;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v24;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v25;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v26;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v27;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v28;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v29;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v30;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v31;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v32;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v33;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v34;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v35;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v36;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v37;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v38;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v39;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v40;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v41;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v42;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v43;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v44;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v45;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v46;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v47;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v48;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v49;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v50;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v51;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v52;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v53;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v54;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v55;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v56;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v57;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v58;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v59;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v60;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v61;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT__register_file_i__DOT__mem__v62;
        CData/*0:0*/ __Vclklast__TOP__clk_i;
        CData/*0:0*/ __Vclklast__TOP__rst_ni;
        CData/*0:0*/ __Vclklast__TOP__soc_top__DOT__cpu_inst__DOT__clk;
        CData/*0:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_trans_ready;
        CData/*0:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__mpu_err_trans_valid;
        VlWide<5>/*159:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__index_nodes;
        VlWide<6>/*191:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__alu_b_cpop_i__DOT__sum;
        CData/*0:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_trans_ready;
        CData/*0:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__wpt_resp_valid;
        SData/*8:0*/ soc_top__DOT____Vcellout__vpu_inst__xif_issue_resp_o;
        IData/*31:0*/ __Vdly__soc_top__DOT__vpu_mem_addr_q;
        IData/*31:0*/ __Vdly__soc_top__DOT__vpu_inst__DOT__vlsu_inst__DOT__cycle_count;
        IData/*17:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__ctrl_byp;
        IData/*31:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__ex_stage_i__DOT__alu_i__DOT__ff_one_i__DOT__sel_nodes;
        QData/*59:0*/ soc_top__DOT____Vcellout__vpu_inst__xif_result_o;
        QData/*37:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT____Vcellout__mpu_i__bus_trans_o;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT____Vcellout__mpu_i__core_resp_o;
        QData/*34:0*/ soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__prefetch_unit_i__DOT__alignment_buffer_i__DOT____Vlvbound3;
        VlWide<3>/*80:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT____Vcellout__mpu_i__bus_trans_o;
        VlWide<3>/*70:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT____Vcellout__mpu_i__core_resp_o;
        VlWide<3>/*70:0*/ soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT____Vcellout__align_check_i__core_resp_o;
    };
    struct {
        VlWide<7>/*200:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__ctrl_fsm;
        QData/*44:0*/ __Vchglast__TOP__soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__gen_seq__DOT__sequencer_i__DOT__decode;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__cpu_inst__DOT____Vcellinp__id_stage_i__rf_rdata_i;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT____Vcellout__id_stage_i__rf_raddr_o;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT____Vcellinp__controller_i__rf_raddr_id_i;
        VlUnpacked<CData/*0:0*/, 1> soc_top__DOT__cpu_inst__DOT____Vcellinp__register_file_wrapper_i__we_i;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT____Vcellinp__register_file_wrapper_i__wdata_i;
        VlUnpacked<CData/*4:0*/, 1> soc_top__DOT__cpu_inst__DOT____Vcellinp__register_file_wrapper_i__waddr_i;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__cpu_inst__DOT____Vcellout__register_file_wrapper_i__rdata_o;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT____Vcellinp__register_file_wrapper_i__raddr_i;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT__id_stage_i__DOT____Vcellinp__decoder_i__rf_raddr_i;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT__controller_i__DOT____Vcellinp__bypass_i__rf_raddr_id_i;
        VlUnpacked<CData/*0:0*/, 1> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT____Vcellinp__register_file_i__we_i;
        VlUnpacked<IData/*31:0*/, 1> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT____Vcellinp__register_file_i__wdata_i;
        VlUnpacked<CData/*4:0*/, 1> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT____Vcellinp__register_file_i__waddr_i;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT____Vcellout__register_file_i__rdata_o;
        VlUnpacked<CData/*4:0*/, 2> soc_top__DOT__cpu_inst__DOT__register_file_wrapper_i__DOT____Vcellinp__register_file_i__raddr_i;
        VlUnpacked<CData/*0:0*/, 6> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vsoc_top__Syms* vlSymsp;  // Symbol table

    // PARAMETERS
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__pma_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_i__DOT__PMA_CFG;
    VlUnpacked<VlWide<3>/*67:0*/, 2> soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__write_buffer_i__DOT__PMA_CFG;
    // enum WData soc_top__DOT__cpu_inst__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__if_stage_i__DOT__mpu_i__DOT__pma_i__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__PMA_CFG  //wide// enum WData soc_top__DOT__cpu_inst__DOT__load_store_unit_i__DOT__mpu_i__DOT__pma_i__DOT__PMA_CFG  //wide
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vsoc_top___024root);  ///< Copying not allowed
  public:
    Vsoc_top___024root(const char* name);
    ~Vsoc_top___024root();

    // INTERNAL METHODS
    void __Vconfigure(Vsoc_top__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
